### ISSUE TITLE
Filterings and associations in Page Resolver

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#257]
* Does active filters object work or is it mocked?
* Handle parameters of SearchCriteria for filterings and associations.

Pagination and sortings work for us.

**Comment by elkmod** [comment]
@mkucmus could you please give an update on what is still required here, given the proposed workaround?

**Comment by elkmod** [comment]
Merged with #258

**Comment by mkucmus** [comment]
we surely can go forward, because #258 is handled also on our side - we successfully implemented it and it's ready to be merged shorty.

The status of this issue is:
[x]  we can attach the associated entities by providing "associations" property in POST `/v1/vsf/page` payload- it's cool to have it, but your workaround does the job, and associations won't be crucial. 

[ ] we still need a possibility to apply filters in the same payload as I described above.  It's for the SSR requests (entering the page with some parameters provided).

Now when I'm passing the "filter" property in the request's payload, It's being ignored like nothing happens on the query parser's side (SW).
I've tried to add an unexistent filter type in the filters array when normally I get 400 Bad Request. But in this case, nothing happens. I guess the filters are ignored within the page resolver's endpoint. 

example of the payload with unreal filter:
```
{
  "filter": [
    {
      "type": "equdwadadaals",
      "field": "namdwadawdae",
      "value": "price"
    }
  ],
  "associations": {
    "options": {
      "associations": {
        "group": {}
      }
    }
  },
  "path": "sports/"
}
```

[ ] - are the `availableFilters` (in resolvers response contained in `listingConfiguration` prop) mocked or real? It's just to confirm whether we can rely on this, but unless the point above is done we don't use it. :v:

**Comment by elkmod** [comment]
Okay, understood. The description I sent you still holds. There's currently no way to use the criteria used within the `/product` endpoint for the `/page` endpoint. Any filters included in the request body will be ignored in the  `/page` endpoint (for the reason, that they are resolved differently). They have to be attached as query parameters as described in the document I sent you.

*As soon as the API changes are implemented, all of the above won't hold anymore.*

**Comment by mkucmus** [comment]
wow, now I get it :) I was blind since I've been following the https://docs.shopware.com/en/shopware-platform-dev-en/api/filter-search-limit?category=shopware-platform-dev-en/api (the filter part). 
I've put those filters (properties, or any others) into filter[    ] format, so at the very beginning I've tried once this way and I gave up this method. So that's why I asked in the comment above about the POST payload :( Totally my bad. The case is closed, thank you @elkmod
