### ISSUE TITLE
[FEATURE] Implement possibility to change view on Product Listing

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/shopware-pwa#655]
### Description

With these icons we will be able to change the grid from SfProductCard to SfProductCardHorizontal

![image](https://user-images.githubusercontent.com/34887212/80351424-93783780-8872-11ea-9389-78dd466b7e13.png)

### Acceptance criteria

- [ ] - implement SfProductCardHorizontal
- [ ] - add toggle functionality to change the view

**Comment by patzick** [comment]
- [ ] implement switch behaviour from https://storybook.storefrontui.io/?path=/story/pages-category--common

**Comment by akrajna** [comment]
On the Horizontal view the quantity field is not working correctly:
- clicking on icons '+' and '-' does not change the quantity 
- if user change the quantity field by writing in some number and click the 'add to the cart' button only one item is added to the cart instead of the number of items user wrote
![Horizontal view](https://user-images.githubusercontent.com/57936972/82796759-5ce40b80-9e76-11ea-8d16-a9df29c6ac66.gif)
