### ISSUE TITLE
SEO URL for detail pages

### ISSUE THREAD

**Issue by theomanus** [DivanteLtd/shopware-pwa#738]
currently the URL of a product page in the shopware-pwa is the like this:
http://localhost:3000/detail/8290109126884ca09733057358e31843

In Shopware Backend Settings -> SEO I created the URL Template for Product Detail Page like this: 
{{ product.translated.name }}/{{ product.productNumber }}
Preview: Main-product-with-advanced-prices/SWDEMO10002

The SEO Index is correctly done and all urls are in table set_url.

In Shopware-PWA the URL of product detail and category pages should be always like the settings in backend.

**Comment by mkucmus** [comment]
hi @theomanus, thanks for the details regarding seoUrls.
Yes, we are aware of lacks of SEO Urls within the listing, so far we are using only the technical URLs because we can't get the seoUrls object in product-listing/page request. 
I will be back with some updates when we prepare mutual solution with Shopware core team :muscle:

**Comment by niklaswolf** [comment]
@mkucmus any news on this? :)

**Comment by mkucmus** [comment]
> @mkucmus any news on this? :)

Yep, It's on the way to be merged right now :+1: 
https://github.com/DivanteLtd/shopware-pwa/pull/1134

will be released in v0.5.0, together with SW v6.4 adjustments stuff 

stay tuned :muscle:
