### ISSUE TITLE
[FEATURE] Implement PATCH invoke in shopware-6 client for plugin usage

### ISSUE THREAD

**Issue by mmeester** [DivanteLtd/shopware-pwa#924]
### Description
At the moment only, GET and POST are available for custom calls, but for some plugins (like the stripe plugin) I need to call a PATCH call

**Comment by patzick** [comment]
hey, thanks @mmeester !

Since [0.2.0](https://github.com/DivanteLtd/shopware-pwa/milestone/7) with context-awareness all the methods will be available API client instance. Example:

```ts
import { getApplicationContext } from "@shopware-pwa/composables"

// later in component
setup(params, {root}) {
  // we can pass component name, to easily track where the context is not passed
  const { apiInstance } = getApplicationContext(root, "myComponent")
  await apiInstance.invoke.patch({
      address: "/some/patch/endpoint",
      payload: {
        some: "payload",
      },
    })
}

```

You can read more about that here: https://shopware-pwa-docs.vuestorefront.io/landing/fundamentals/security.html#context-awareness
`Invoke` interface: https://shopware-pwa-docs.vuestorefront.io/landing/resources/api/shopware-6-client.shopwareapiinstance.invoke.html

I'm closing this issue for now, hope it helps you :)

**Comment by mmeester** [comment]
When is 0.2.0 expected to be released
